# Generated by Django 3.0.2 on 2020-05-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account_detail',
            table='Social_Account_detail',
        ),
    ]
