# Generated by Django 3.0.2 on 2020-05-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200530_1205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account_detail',
            table=None,
        ),
    ]
