# Generated by Django 3.0.2 on 2020-05-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200530_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(max_length=400, null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account_detail')),
            ],
            options={
                'db_table': 'Social_user_post',
            },
        ),
        migrations.CreateModel(
            name='Post_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(null=True)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account_detail')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User_post')),
            ],
            options={
                'db_table': 'Social_post_like',
            },
        ),
    ]
