# Generated by Django 3.0.2 on 2020-05-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200530_1742'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post_like',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user_post',
            table=None,
        ),
    ]
